name: ea
description: ea
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
